---
driver:
  name: docker
  hostname: dogtag.ci.local
  use_sudo: true


provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: debug
  formula: dogtag
  grains:
    noservices: True
    service: service
    systemd: False
    providers:
      service: service
  state_top:
    base:
      "*":
        - dogtag
  pillars:
    top.sls:
      base:
        "*":
          - dogtag

verifier:
  name: inspec
  sudo: true

platforms:
  - name: <%= ENV['PLATFORM'] || 'ubuntu-xenial' %>
    driver_config:
      image: <%= ENV['PLATFORM'] || 'trevorj/salty-whales:xenial' %>
      platform: ubuntu

suites:

  - name: dogtag
    provisioner:
      pillars-from-files:
        dogtag.sls: tests/pillar/dogtag_single.sls
